CREATE TABLE FILECONVERTER.FILES (
ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(30),
SIZE DECIMAL,
FORMAT VARCHAR(10),
CONVERTED TIMESTAMP
);